<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Title>John Cronan's Command Line Parser</Title>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/john-cronan/main</RepositoryUrl>
    <PackageTags>Command Line;Command Line Parser</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <Description>An easy to use, strongly-typed, and versatile command line parser.</Description>
    <Authors>John Cronan</Authors>
    <Version>3.0.0</Version>
    <PackageReleaseNotes>3.0.0 - Improved support for complex command lines, where a single utility handles multiple commands (a la the dotnet and azure CLIs), including a CommandDispatcher.

2.0.0 - Addition of "help switches". The presence of a defined help switch on a command line weakens ordinary validation (parse errors surface as warnings instead), so that a command line that doesn't really need to be valid anyway (help is being requested) can be parsed.</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="CommandLineParser.cs~RF33d7df9c.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
